### ISSUE TITLE
FFMPEG AAC blocking on NaN/Inf input

### ISSUE THREAD

**Issue by pmjdebruijn** [jliljebl/flowblade#842]
Flowblade version 2.4.0.1 / Ubuntu 20.04

Currently the only render preset that seems to work entirely properly is: Lossless FFv1 (which is a workable solution in my case)

H.264 / .mp4 seems to not write any data to my output file, but when I export an MLT XML the melt command does export a H.264 encoded mp4....

Is there any debug flags I can enable to see why Flowblade renderer get's stuck, while melt does not...

**Comment by jliljebl** [comment]
What the hell...I don't know what is going on.

Maybe ffmpeg has stopped supporting some render args and we are sending them the old wrong style args? Something like this happened once before.

Can you try changing args in */res/render/renderencoding.xml* to see if there is some difference?

If/when the Ubuntu 20.04 is out I can try to reproduce here.

**Comment by pmjdebruijn** [comment]
Small clarification, most other presets do export a file, however with crackling sounds, that may be due to having mixed sampling rates in my project. I have 48kHz amongst the other 44kHz files, I'll try to test that over the next few days.

It's only H.264 which completely blocks exporting at all, I can just see the estimated export time increasing until the cows come home.

I've already tried playing a bit with renderencoding.xml to not much avail.

Is there any code I can insert somewhere to maybe debug this a little better on my end?

**Comment by jliljebl** [comment]
> Is there any code I can insert somewhere to maybe debug this a little better on my end?

No, not really, If running from terminal does not give anything. The H.264 problem has been seen elsewhere.

BTW, which MLT version you have?

You can test audio by:
1) File->Export->MLT XML
2) Open that in Kdenlive or shotcut
3) render from those apps.

is the result different?

**Comment by pmjdebruijn** [comment]
melt 6.20.0
BTW, the audio popping I cant reproduce with melt, so that's not really a flowblade problem I guess...

**Comment by pmjdebruijn** [comment]
Only this (which seems unrelated), time.clock() apparently no longer works in python 3.8:

Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 195, in <lambda>
    ('Save', None, _('_Save'), '<control>S', None, lambda a:projectaction.save_project()),
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 424, in save_project
    _save_project_in_last_saved_path()
  File "/usr/share/flowblade/Flowblade/projectaction.py", line 448, in _save_project_in_last_saved_path
    save_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'

replacing time.clock() with time.process_time() makes that error go away, with no improvement on the export itself.

**Comment by pmjdebruijn** [comment]
Ah that's already fixed in master:
https://github.com/jliljebl/flowblade/commit/bc23af39c84b8e9c3de0a97bd6fe48bd1b0619c9

**Comment by pmjdebruijn** [comment]
The file written is only 863 bytes, presumably that's just the MP4 header?

To put things into perspective, the FFv1 export takes about a minute or so.

After some experimentation, i'm beginning to suspect audio is playing a larger role...

acodec=flac
vcodec=libx264
b=8000k

exports fine. so libx264 in of itself isn't an issue.

**Comment by jliljebl** [comment]
> acodec=flac
vcodec=libx264
b=8000k

>exports fine. so libx264 in of itself isn't an issue.

Ok, thanks for the research. Several H.264 encodings are the only ones with "acodec=aac", this is very much the likely cause. I'll change to "acodec=flac".

Since this does not reproduce on my system, but you have provided enough circumstantial evidence that I put this fix having probability to fix everyone's issues at 95%.

**Comment by pmjdebruijn** [comment]
I don't think FLAC works in MP4, I switch it to mkv just to test.
And I'm almost 100% sure AAC worked a few months back, but that was using different versions of MLT/ffmpeg.
I'll do some more digging over the next few days, I'll keep you posted.

**Comment by dvdlvr** [comment]
Hi, Just a few questions, if you don't mind. When you are rendering the MLT xml with melt are you using the same parameters as Flowblade gives you when you click on the user parameters in the render panel? Do you happen to have the performace setting in the preferences set to a specific setting? If that is set too high it sometimes causes problems. If it is set to anything else than 1, please set it to 1 and try again. And make sure 'drop frames' is unticked. Thanks. Steven.

**Comment by jliljebl** [comment]
It seems we moved to AAC just lately: https://github.com/jliljebl/flowblade/commit/928bfba9b6103375f269950148f26f682a539ad8#diff-a5aef0309824be122f89f41cfc4384f5

 I'll drop AAC and see what Shotcut and KDEnlive are using and use that.

**Comment by pmjdebruijn** [comment]
I know, since I submitted the patch for it, but as I stated, anything else than flac locks up export. libmp3lame doesn't work either. As I said, I'll do some more testing soon.

(BTW I have render threads set to 1, and drop frames unticked)

**Comment by jliljebl** [comment]
KDEnlive and Shotcut have AAC as well. This is something else. I'm suspecting something Python 3 related.

**Comment by jliljebl** [comment]
Did some tests. not Python 3 related probably.

**Comment by jliljebl** [comment]
@pmjdebruijn  There is file *$HOME/,cache/flowblade/log_single_render* that holds terminal output for rendering from render panel. I think the best debug thing we can get. For H.264/.mp4 render I get the following:

    [aac @ 0x7ffae8204fc0] Too many bits 170666.666667 > 12288 per frame requested, clamping to max
    [mp4 @ 0x7ffae8200f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    [mp4 @ 0x7ffae8200f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.

Do you get something different?

**Comment by dvdlvr** [comment]
I'm using H.264 / mp4 (AAC) all the time on Flowblade 2.2 and MLT 2.16.
It works without any problem whatsoever.

The messages for aac clamping to max and AVstream.codec also show up in 
my log, so those are old messages.

I'm downloading the flatpak of 2.4 now to see how it behaves on my files.

**Comment by pmjdebruijn** [comment]
I just reconstructed a similar project, and export seemed to work fine. So there's a large chance this is quite the cornercase, where something specific in my project triggers this.

I'll do more test over the next few days. I'll keep you posted.

**Comment by dvdlvr** [comment]
I rendered a 1080p @25fps H.264 / .mp4 (AAC) at 8000 kb/s with flatpak 2.4.0 (with MLT 2.18) without any problem whatsoever.

**Comment by jliljebl** [comment]
Yeah, this is I believe fundamentally duplicate of https://github.com/jliljebl/flowblade/issues/791

I had this...and then it went away. Go figure.

Keeping both these still open, other users seem to keep having this and I would really like to know what is going on.

**Comment by smolnp** [comment]
I have use "acodec=flac" makes final render last several times longer. (fedora 31, flowblade master, mlt 6.20.0).

**Comment by pmjdebruijn** [comment]
**~/.cache/flowblade/log_single_render**
```
[matroska,webm @ 0x7fea9cbf7380] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fea9cf0bd40] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[aac @ 0x7fea88204d80] Too many bits 170666.666667 > 12288 per frame requested, clamping to max
[mp4 @ 0x7fea88200f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x7fea88200f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[aac @ 0x7fea88204d80] Input contains (near) NaN/+-Inf
[consumer avformat] error with audio encode: -22 (frame 3)
[aac @ 0x7fea88204d80] Input contains (near) NaN/+-Inf
[consumer avformat] error with audio encode: -22 (frame 4)
[aac @ 0x7fea88204d80] Input contains (near) NaN/+-Inf
[consumer avformat] error with audio encode: -22 (frame 4)
[aac @ 0x7fea88204d80] 5 frames left in the queue on closing
```

My console only reports:
```
[matroska,webm @ 0x2e26580] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[matroska,webm @ 0x7fd732231500] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[matroska,webm @ 0x7fd732629080] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
[wav @ 0x7fd732a45840] Value 1.000000 for parameter 'seekable' out of range [-1 - 0]
```

**Comment by pmjdebruijn** [comment]
I just used the "Render using args" function to play with settings, but changing the codec to libmp3lame seems to work fine as well... 

So it seems to be a subtle issue in one of my input files, is causing a fairly bad problem in ffmpeg's aac encoder... However...

The strange thing is, when I manually aac encode my audio files with ffmpeg, it works just fine.
When I import the same source files into a new flowblade project, and export with aac, it works just fine as well, contradicting the idea the problem is in the source files.

This sortof leaves me to believe that the bad audio frames are potentially being generated internally in MLT due to some cut that was being made.

**Comment by jliljebl** [comment]
Closing via #852.
