### ISSUE TITLE
Shortcut keys not working.

### ISSUE THREAD

**Issue by tonycsa** [jliljebl/flowblade#1011]
Hello everyone.

I just bought a new hard drive, so thought i would install latest Kubuntu.
Installed Flowblade from Discover, went through the dialog and chose standard method instead of studio. 
Copied files from old drive .local/Share/Flowblade/Rendered_Clips to new drive, so i can continue to work on projects.
Pressing mapped keyboard keys doesn't do anything. However, Ctrl-Z still works as undo.
Edit>Keyboard Shortcuts doesn't open any dialog boxes, just ignores request. 
Hovering over button shows the what the shortcut keys should be.
Removed from Discover, and reinstalled through Command line.
Still same issue. 
Restarting system does nothing to help.

Any help in resolving this issue would be greatly appreciated, as it takes twice the time to do edits without the shortcuts
Thanks,
Tony

My suspicion is that this is an issue with the latest release of Kubuntu, But thought I would post for support/a resolution here.

1) Flowblade version (Help->About):2.6.0
2) MLT version (Help->Runtime Environment):6.24.0
3) Your distribution (Ubuntu, Debian, Mint etc.):Kubuntu 21.04(Fresh installation, worked fine on previous 20.04)
4) If possible, try to provide step-by-step instructions...:

**Comment by nolka** [comment]
When try to open shortcuts window, got exception:
```
Traceback (most recent call last):
  File "/usr/share/flowblade/Flowblade/editorwindow.py", line 287, in <lambda>
    ('KeyboardShortcuts', None, _('Keyboard Shortcuts'), None, None, lambda a:dialogs.keyboard_shortcuts_dialog(self.window, workflow.get_tline_tool_working_set, menuactions.keyboard_shortcuts_callback)),
  File "/usr/share/flowblade/Flowblade/dialogs.py", line 1408, in keyboard_shortcuts_dialog
    diff_data.set_text(shortcuts.get_diff_to_defaults(editorpersistance.prefs.shortcuts))
  File "/usr/share/flowblade/Flowblade/shortcuts.py", line 170, in get_diff_to_defaults
    key_name_test, action_name = get_shortcut_info(test_root, code)
  File "/usr/share/flowblade/Flowblade/shortcuts.py", line 146, in get_shortcut_info
    events = root.getiterator('event')
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'

```

**Comment by tonycsa** [comment]
Ended up having to re-install via Flatpak. Selected "Movie Editor" style and seems to work fine now, originally didn't select "Movie Editor", i think the problem stemmed from there. Had issues with selecting the Edit>Keyboard Shortcuts wasn't working either.
Sorry @nolka didn't edit files to the level you were suggesting, figured i would clear up other possible issues with the re-install.
Thanks.

**Comment by jliljebl** [comment]
This was fixed for 2.8 there is a patch removing the depraceted *getiterator* method:

https://github.com/jliljebl/flowblade/commit/5467759cb1559fb05a0c3a7a28aaa0a54044d1db#diff-1a602e9c5fdc44c43dcba43a734c8d91f189226d8177a345b608ef24508fc605
